# Generated by Django 5.0 on 2023-12-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_event_attendees_alter_event_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='event',
        ),
        migrations.AddField(
            model_name='task',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='manager.event'),
        ),
    ]
